const ERRORS = {
  TOKEN_MISSING: 401,
  TOKEN_EXPIRED: 402,
  INVALID_BEARER_AUTHORIZATION: 403,
  USER_NOT_FOUND: 600,
  EMAIL_ALREADY_EXISTS: 601,
  INVALID_PASSWORD: 603,
  ARTICLE_NOT_FOUND: 604,
  INVALID_ID: 605,
  INVALID_PERMISSION: 606,

};

module.exports = ERRORS;
